### ISSUE TITLE
PLAIN authentication failed with condition SASL failure: not-authorized

### ISSUE THREAD

**Issue by Perflyst** [iNPUTmice/caas#67]
I try to test some local telephone SIP system which also can be (ab)used for normal xmpp chat messages. The IP address behind the domain is a private IP starting with 10.200.x.x
Sadly this fails (auth via e.g. Gajim or Dino works):
```
rocks.xmpp.core.sasl.AuthenticationException: PLAIN authentication failed with condition SASL failure: not-authorized
        at rocks.xmpp.core.session.AuthenticationManager.processNegotiation(AuthenticationManager.java:149)
        at rocks.xmpp.core.stream.client.StreamFeaturesManager.handleElement(StreamFeaturesManager.java:212)
        at rocks.xmpp.core.session.XmppSession.handleElement(XmppSession.java:1210)
        at rocks.xmpp.core.net.client.XmppStreamReader.lambda$startReading$0(XmppStreamReader.java:169)
        at rocks.xmpp.util.concurrent.QueuedExecutorService.doExecute(QueuedExecutorService.java:154)
        at rocks.xmpp.util.concurrent.QueuedExecutorService.lambda$poll$0(QueuedExecutorService.java:126)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by iNPUTmice** [comment]
This is either a bug in the underlying [XMPP library](https://bitbucket.org/sco0ter/babbler/src/master/) or in the XMPP server. Feel free to make it reproducible with a small snippet of the library and report it upstream. But especially since this is a private deployment there is nothing I can do about that.

**Comment by Perflyst** [comment]
I also tested the old compliance tester, which also failed.
Then I noticed the password contains special chars, ! and &. I changed it to numbers and letters only and it worked!
